#!/bin/sh -x
# dwf, aka "Done With Feature" script: deletes current branch and puts you back on master
ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 0
CURRENT="${ref#refs/heads/}"
if [ -n "$1" ]; then
	master_branch=$1
else
	if [ -n "$(git branch --list main)" ]; then
		master_branch="main"
	else
		master_branch="master"
	fi
fi
git checkout ${master_branch}
git branch -d ${CURRENT}